services:

  web:
    build: .
    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mariadb;Port=3306;Database=nabohjelp;User=nabohjelp_user;Password=nabohjelp_password;"

    depends_on:
      mariadb:
        condition: service_healthy


  mariadb:
    image: mariadb:12

    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: nabohjelp
      MARIADB_USER: nabohjelp_user
      MARIADB_PASSWORD: nabohjelp_password

    ports:
      - "3306:3306"

    volumes:
      - nabohjelp_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  nabohjelp_data: